---
project:
  type: website

website:
  title: "shaduw-langs-de-snelweg"
  navbar:
    left:
    - text: "Examples"
      menu:
      - examples/notebooks/introduction.ipynb
    - text: map
      href: examples/stops_shade_map_PoC.html
    - text: "Python API"
      file: reference/index.qmd
    right:
    - icon: github
      href: https://github.com/HKV-products-services/shaduw-langs-de-snelweg
      aria-label: GitHub
format:
  html:
    theme: cosmo
    toc: true

quartodoc:
  style: pkgdown
  dir: reference
  title: API Reference
  package: shaduw_langs_de_snelweg
  parser: numpy
  dynamic: True
  rewrite_all_pages: True
  options:
    include_inherited: true
    include_empty: true
    include_attributes: true
    include_classes: true
    include_functions: true
